### ISSUE TITLE
Huge span on iPhone X 

### ISSUE THREAD

**Issue by mcproj** [Muirey03/Duo#2]
I got span between status bar and cc items enlarged right after I installed this tweak. 
iOS 11.2.1 iPhone X

**Comment by Muirey03** [comment]
Please attach a screenshot. What iOS version are you on?

**Comment by mcproj** [comment]
iOS 11.2.1
![image](https://user-images.githubusercontent.com/4383849/43184202-626212a8-901a-11e8-9e7e-58afc7405210.png)

**Comment by Muirey03** [comment]
Fixed in v.1.0.1
